<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Xunit.SkippableFact" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Andes.Extensions.AI.Mcp\Andes.Extensions.AI.Mcp.csproj" />
    <ProjectReference Include="..\Andes.Extensions.AI.TestMcpServer\Andes.Extensions.AI.TestMcpServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Andes.Extensions.AI.Integration.Test\AzureOpenAIFixture.cs" Link="AzureOpenAIFixture.cs" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Andes.Extensions.AI.Integration.Test\appsettings.integration.json"
          Condition="Exists('..\Andes.Extensions.AI.Integration.Test\appsettings.integration.json')"
          Link="appsettings.integration.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
